name: Deploy
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd functions
          npm install
      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - name: Deploy to Firebase
        run: |
          cd functions
          npm i firebase-tools
          npm run deploy
